### ISSUE TITLE
Cannot start app after installation 

### ISSUE THREAD

**Issue by tomekk89** [eskerda/slack-keep-presence#10]
slack-keep-presence -h

/home/tomek/node_modules/slack-keep-presence/index.js:9
class SlackPresence {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tomek/node_modules/slack-keep-presence/app.js:12:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by ph3l1x** [comment]
I am having the exact same issue.

./slack-keep-presence -h
/home/phelix/node_modules/slack-keep-presence/index.js:9
class SlackPresence {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/phelix/node_modules/slack-keep-presence/app.js:12:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by tomekk89** [comment]
Old version of NodeJS on Ubuntu was the cause of it
Try this:

> curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs
