### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by drnushooz** [eskerda/slack-keep-presence#2]
This exception pops up randomly on my Mac.

```
/Users/abhinavchawade/node_modules/slack-keep-presence/index.js:113
        var mention = data['text'].indexOf(this.user_id) >= 0;
                                  ^

TypeError: Cannot read property 'indexOf' of null
    at SlackPresence.handle_message (/Users/abhinavchawade/node_modules/slack-keep-presence/index.js:113:35)
    at slackAPI.emit (/Users/abhinavchawade/node_modules/eventemitter3/index.js:116:35)
    at /Users/abhinavchawade/node_modules/slackbotapi/lib/index.js:80:22
    at WebSocket.<anonymous> (/Users/abhinavchawade/node_modules/slackbotapi/lib/index.js:215:24)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/abhinavchawade/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/abhinavchawade/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/Users/abhinavchawade/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/abhinavchawade/node_modules/ws/lib/Receiver.js:508:14
```

**Comment by eskerda** [comment]
Issue should be fixed, can you try upgrading?

Depending on how you have it installed it varies. On this case, it's on local node_modules, so I assume to upgrade one must `npm install slack-keep-presence` to get latest version?

once done, `npm outdated` should not display `slack-keep-presence`

Feel free to reopen this issue if error persists.

**Comment by eskerda** [comment]
I didn't know packages under home would not update without a package.json file... maybe I should update the readme to make the installation with `-g` flag.
