### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by Seanmatthews** [eskerda/slack-keep-presence#5]
Used `sudo npm install slack-keep-presence -g` on OS X El Capitan. Receive the following when trying to run:

```
/usr/local/lib/node_modules/slack-keep-presence/index.js:8
const notifier = require('node-notifier');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/slack-keep-presence/app.js:12:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by eskerda** [comment]
This is probably fixed by https://github.com/eskerda/slack-keep-presence/pull/6

**Comment by feebala** [comment]
Hm, I'm actually having this issue too. Any suggestions? I saw you're not developing this further, but if there's a quick workaround I could use, that would be great. Thanks!

**Comment by eskerda** [comment]
@feebala Actually, this issue should be fixed. Can you post the exact output of the error? Thanks!

(slack-keep-presence is no developed further, but still maintained!)

**Comment by Seanmatthews** [comment]
@feebala If you're still having problems, I made this workaround for Mac: https://gist.github.com/Seanmatthews/f4576232e9944c20d7d099cd34c65d5a

**Comment by feebala** [comment]
@eskerda Sure - here's the output:

> class SlackPresence {
^^^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/slack-keep-presence/app.js:12:21)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)

**Comment by feebala** [comment]
@Seanmatthews thanks! Is that a standalone fix that keeps slack active?

**Comment by eskerda** [comment]
What ancient versions of node are you all using?

```$ node --version```

**Comment by BigPrimeNumbers** [comment]
I am running into this issue as well, with the same exact output as @feebala. I'm running node v5.12.0.
