### ISSUE TITLE
Block-Scoped Declarations Not Yet Supported Outside of Strict Mode

### ISSUE THREAD

**Issue by BigPrimeNumbers** [eskerda/slack-keep-presence#8]
I am running into an issue getting this to run on my system. I get the following error:

```
class SlackPresence {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/redacted/node_modules/slack-keep-presence/app.js:12:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Node v5.12.0

**Comment by BigPrimeNumbers** [comment]
Fixed by upgrade to node version 6.10.3 :)
