### ISSUE TITLE
Crash after IM List Cache ready

### ISSUE THREAD

**Issue by lallenlowe** [eskerda/slack-keep-presence#9]
```./node_modules/slack-keep-presence/app.js -t <token>
04:31:27s 560ms [Info]      [SlackPresence] Getting my user id
04:31:27s 919ms [Info]      [SlackPresence] Found <id>
04:31:28s 279ms [Info]      [SlackPresence] IM list cache ready
/Users/user/node_modules/slack-keep-presence/index.js:194
       _.each(data['members'], function(user) {
                  ^

TypeError: Cannot read property 'members' of undefined
    at SlackPresence.store_users (/Users/user/node_modules/slack-keep-presence/index.js:194:19)
    at Request.<anonymous> (/Users/user/node_modules/slack-node/lib/lib/slack.seed.js:118:49)
    at Request._callback (/Users/user/node_modules/lodash/lodash.js:10067:25)
    at Request.requestRetryReply [as reply] (/Users/user/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/Users/user/node_modules/requestretry/index.js:133:10)
    at Request.self.callback (/Users/user/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/user/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)```

**Comment by lallenlowe** [comment]
I used to be able to use this same version successfully
